version: "3.7"
networks:
  tracker-network:
    driver: bridge
  location-network:
    driver: bridge
services:
  trackit-redis:
    container_name: trackit-redis
    image: "redis:6.0.19-alpine"
    networks:
      - tracker-network
    restart: on-failure

  trackit-rabbit:
    container_name: trackit-rabbit
    image: "rabbitmq:3-management"
    ports:
        - "5672:5672"
        - "8000:15672"
    networks:
      - tracker-network
      - location-network
    restart: on-failure
    environment:
      - RABBITMQ_DEFAULT_USER=dath
      - RABBITMQ_DEFAULT_PASS=rxpFm6!st3C089

  trackit-postgres:
    container_name: trackit-postgres
    image: postgis/postgis:12-2.5-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=p2X3hP2Hfn61%h
      - POSTGRES_USER=dath
      - POSTGRES_DB=TrackItDB
    ports:
      - "5432:5432"
    networks:
      - location-network

  tracker-service:
    build:
      context: ./tracker-service
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    networks:
      - tracker-network
    depends_on:
      - trackit-redis
      - trackit-rabbit
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=deploy


  location-service:
    build:
      context: ./location-service
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    networks:
      - location-network
    depends_on:
      - trackit-rabbit
      - trackit-postgres
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=deploy

  trackit-ui:
    build:
      context: ./track-it-ui
      dockerfile: Dockerfile
    ports:
    - "80:80"
    networks:
      - location-network
    restart: on-failure
